const { BloomFilter } = require("./bloom-filter-desafio");

const palavrasInseridas = [
  "amor",
  "casa",
  "carro",
  "computador",
  "tecnologia",
  "desenvolvimento",
  "programacao",
  "javascript",
  "algoritmo",
  "estrutura",
  "dados",
  "filtro",
  "bloom",
  "memoria",
  "otimizacao",
  "eficiencia",
  "sistema",
  "servidor",
  "banco",
  "seguranca",
  "criptografia",
  "chave",
  "valor",
  "indice",
  "funcao",
  "objeto",
  "classe",
  "metodo",
  "codigo",
  "projeto",
  "teste",
  "erro",
  "sucesso",
  "usuario",
  "senha",
  "email",
  "perfil",
  "internet",
  "rede",
  "conexao",
  "protocolo",
  "roteador",
  "sinal",
  "velocidade",
  "informacao",
  "conhecimento",
  "ciencia",
  "pesquisa",
  "estudo",
  "livro",
  "escola",
  "universidade",
  "professor",
  "aluno",
  "aula",
  "curso",
  "trabalho",
  "empresa",
  "negocio",
  "mercado",
  "economia",
  "dinheiro",
  "investimento",
  "lucro",
  "carreira",
  "futuro",
  "passado",
  "presente",
  "tempo",
  "relogio",
  "calendario",
  "dia",
  "noite",
  "manha",
  "tarde",
  "sol",
  "lua",
  "estrela",
  "planeta",
  "universo",
  "galaxia",
  "espaco",
  "astronauta",
  "foguete",
  "satelite",
  "natureza",
  "arvore",
  "floresta",
  "animal",
  "planta",
  "terra",
  "agua",
  "fogo",
  "vento",
  "vida",
  "musica",
  "filme",
  "cinema",
  "bola",
  "jogo",
];

const palavrasTeste = [
  "zebra",
  "banana",
  "laptop",
  "manga",
  "piano",
  "foguete2",
  "xadrez",
  "quartzo",
  "yoga",
  "vitrola",
  "quimica",
  "lampada",
  "safira",
  "pimenta",
  "roblox",
  "tetera",
  "onibus",
  "microfone",
  "caixote",
  "tucano",
  "escudo",
  "palheta",
  "sorvete",
  "cubo",
  "tijolo",
  "dicionario",
  "microscopia",
  "brinco",
  "cachoeira",
  "aviao",
  "escada",
  "caminhao",
  "barra",
  "selo",
  "nevoa",
  "passeio",
  "botao",
  "lapis",
  "caderno",
  "martelo",
  "Vassoura",
  "garrafa",
  "farol",
  "folha",
  "buraco",
  "candido",
  "torre",
  "moldura",
  "espelho",
  "janela",
  "cortina",
  "tapete",
  "cadeira",
  "mesa",
  "colher",
  "prato",
  "garfo",
  "molho",
  "doce",
  "sal",
  "pimenta",
  "algodao",
  "madeira",
  "fita",
  "ferramenta",
  "monitor",
  "teclado",
  "mouse",
  "celular",
  "tablet",
  "pendrive",
  "cabos",
  "tomada",
  "energia",
  "noz",
  "alface",
  "tomate",
  "cebola",
  "frango",
  "peixe",
  "leite",
  "cafe",
  "cha",
  "bolacha",
  "pao",
  "manteiga",
  "cavalo",
  "trem",
  "passeio",
  "futebol",
  "viagem",
  "computador2",
  "marte",
  "lago",
  "caderno",
  "janela",
  "camisa",
  "prateleira",
  "escova",
  "telefone",
];

// Você deve escolher o tamanho(x) do array e a quantidade(y) conforme achar melhor
const bloom = new BloomFilter(x,y); 

const inicioInsercao = performance.now();

for (const palavra of palavrasInseridas) {
  bloom.add(palavra);
}

const fimInsercao = performance.now();
const tempoInsercao = fimInsercao - inicioInsercao;


let falsosPositivos = 0;
const inicioBusca = performance.now();

for (const palavra of palavrasTeste) {
  if (bloom.contains(palavra)) {
    falsosPositivos++;
  }
}

const fimBusca = performance.now();
const tempoBusca = fimBusca - inicioBusca;

console.log("Tempo de inserção:", tempoInsercao.toFixed(4), "ms");
console.log("Palavras inseridas:", palavrasInseridas.length);
console.log("Palavras testadas:", palavrasTeste.length);
console.log("Tempo de busca:", tempoBusca.toFixed(4), "ms");
console.log("Falsos positivos:", falsosPositivos);
console.log(
  "Taxa:",
  ((falsosPositivos / palavrasTeste.length) * 100).toFixed(2) + "%",
);
